Fix GET warning notes
When the GET `warningnotes/{id}` is called, the API returns a 500.
From investigating the logs, the error returned by the lambda read:
`Unknown error responding to request: InvalidCastException:
System.InvalidCastException: Column is null`

It looks like Entity Framework returns this error when we've
set up columns as required in the infrastructure when the actual
database schema has the columns as NULLABLE.

This removes the extra `[required]` tags within the Warning Notes
Infrastructure Class